spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  profile: dev
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
---
server:
  port: 8202
spring:
  profile: test

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
